const root=process.argv[2],kind=process.argv[3],W=require(root+'/node_modules/ws');const sleep=ms=>new Promise(r=>setTimeout(r,ms));let clients=[];const checks=[];
async function connect(token){const ws=new W('ws://127.0.0.1:16068/'+token);let output='';ws.on('message',d=>output+=d.toString());await new Promise((r,j)=>{ws.on('open',r);ws.on('error',j)});clients.push(ws);return{ws,text:()=>output}}
function check(ok,name){checks.push({name,ok});if(!ok)throw Error(name)}
(async()=>{let c=await connect('perf');c.ws.send('stty -echo\n');await sleep(150);c.ws.send("printf 'PERSIST_012345\\n'\n");await sleep(200);check(c.text().includes('PERSIST_012345'),'initial output');c.ws.terminate();await sleep(100);
for(let i=0;i<40;i++){c=await connect('perf');await sleep(10);c.ws.terminate();await sleep(10)}
c=await connect('perf');await sleep(200);check(c.text().includes('PERSIST_012345'),'reconnect preserves history');c.ws.send("printf 'ONCE_765432\\n'\n");await sleep(150);c.ws.terminate();await sleep(50);c=await connect('perf');await sleep(200);check(c.text().split('ONCE_765432').length-1===1,'history appended once');
c.ws.send('exit\n');await sleep(500);c.ws.terminate();c=await connect('perf');c.ws.send("printf 'AFTER_EXIT_OK\\n'\n");await sleep(200);check(c.text().includes('AFTER_EXIT_OK'),'shell death recovers');c.ws.send('closeXtermHandlerCommand');await sleep(100);c.ws.terminate();
const many=await Promise.all(Array.from({length:8},(_,i)=>connect('multi'+i)));for(const c of many)c.ws.send("for i in {1..100}; do printf 'moderate %s\\n' \"$i\"; done\n");await sleep(500);for(const c of many)check(c.text().includes('moderate 100'),'multi-client output');for(const c of many)c.ws.terminate();await sleep(100);for(let i=0;i<8;i++){c=await connect('multi'+i);c.ws.send('closeXtermHandlerCommand');await sleep(60);c.ws.terminate()}
console.log(JSON.stringify({kind,checks,passed:true}));})().catch(e=>{console.error(e);console.log(JSON.stringify({kind,checks,passed:false}));process.exitCode=1}).finally(()=>{for(const c of clients)c.terminate()});
